apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultapp
  template:
    metadata:
      labels:
        app: vaultapp
      annotations:  # Add the annotations here
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-config: internal/data/db/config
        vault.hashicorp.com/agent-inject-status: update
        vault.hashicorp.com/agent-inject-template-config: |-
          {{- with secret "internal/data/db/config" -}}
          export DB_HOST={{ .Data.data.host }}
          export DB_USER={{ .Data.data.user }}
          export DB_PASSWORD={{ .Data.data.password }}
          export DB_DATABASE={{ .Data.data.database }}
          {{- end -}}
        vault.hashicorp.com/role: internal-app
    spec:
      serviceAccountName: internal-app
      containers:
        - name: vaultapp
          image: gitopsdemo2023.azurecr.io/vaultapp:2.8
          ports:
            - containerPort: 8080
          command:
            ['/bin/bash', '-c']
          args:
            ['source /vault/secrets/config && python app.py']
      imagePullSecrets:  # Add this section
        - name: docker-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: vaultapp-service
spec:
  selector:
    app: vaultapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
